targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
           - web/**.dart
           - test/**.dart
        release_options:
          dart2js_args:
            - --fast-startup
            - --minify
            - --trust-type-annotations
            - --trust-primitives