name: garden_planner
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
author: James Hurford <terrasea@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.11.0
  angular_forms: ^2.0.0

dependency_overrides:
  dart_internal: 0.1.2
#  angular:
#    git:
#      url: git@github.com:dart-lang/angular.git
#      path: angular
#  angular_compiler:
#    git:
#      url: git@github.com:dart-lang/angular.git
#      path: angular_compiler
#  angular_ast:
#    git:
#      url: git@github.com:dart-lang/angular.git
#      path: angular_ast
#  angular_forms:
#    git:
#      url: git@github.com:dart-lang/angular.git
#      path: angular_forms
#  collection:
#    git: git@github.com:dart-lang/collection.git
#  angular_components:
#    git: git@github.com:dart-lang/angular_components.git

#dev_dependencies:
#  build_runner: ^0.8.2
#  build_test: ^0.10.1+1
#  build_web_compilers: ^0.4.0
#  sass_builder: ^2.0.0
#  angular_test: any
#  test: any
#  pageloader: ^3.0.0-alpha

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.5.1
  angular_test: ^2.2.0